config/routes.rb
Rails.application.routes.draw do

  root 'top#index'

  devise_for :guardians

  resources :settings, :only => [:index]
  resources :contents, :except => [:show]
  resources :activities, :except => [:show]
  resources :guardians, :except => [:index, :new]
  resources :wards, :except => [:show]

  resources :reports, :only => [:index] do
    collection do
      get 'selection'
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/ward.rb
# == Schema Information
#
# Table name: wards
#
#  id          :integer          not null, primary key
#  name        :string
#  address     :string
#  tel         :string
#  sex         :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  guardian_id :integer
#

class Ward < ApplicationRecord
  belongs_to :guardian
  has_many :activities
  has_many :families
  enum sex: { male: 1, female: 2 }
end

app/controllers/wards_controller.rb
class WardsController < ApplicationController
  before_action :set_ward, only: [:edit, :update, :destroy]

  # GET /wards
  # GET /wards.json
  def index
    @wards = current_guardian.wards
  end

  # GET /wards/new
  def new
    @ward = Ward.new
  end

  # GET /wards/1/edit
  def edit
  end

  # POST /wards
  # POST /wards.json
  def create
    @ward = Ward.new(ward_params)

    respond_to do |format|
      if @ward.save
        format.html { redirect_to wards_path, notice: 'Ward was successfully created.' }
        format.json { render :show, status: :created, location: @ward }
      else
        format.html { render :new }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wards/1
  # PATCH/PUT /wards/1.json
  def update
    respond_to do |format|
      if @ward.update(ward_params)
        format.html { redirect_to wards_path, notice: 'Ward was successfully updated.' }
        format.json { render :show, status: :ok, location: @ward }
      else
        format.html { render :edit }
        format.json { render json: @ward.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wards/1
  # DELETE /wards/1.json
  def destroy
    @ward.destroy
    respond_to do |format|
      format.html { redirect_to wards_url, notice: 'Ward was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ward
      @ward = Ward.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ward_params
      params.require(:ward).permit(:name, :address, :tel, :sex, :guardian_id)
    end
end

app/views/wards/_form.html.erb
<%= form_with(model: ward, local: true) do |form| %>
  <% if ward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ward.errors.count, "error") %> prohibited this ward from being saved:</h2>

      <ul>
      <% ward.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ward_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :ward_address %>
  </div>

  <div class="field">
    <%= form.label :tel %>
    <%= form.text_field :tel, id: :ward_tel %>
  </div>

  <div class="field">
    <%= form.label :sex %>
    <%= form.select :sex, Ward.sexes_i18n.invert, id: :ward_sex %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wards/edit.html.erb
<h1>Editing Ward</h1>

<%= render 'form', ward: @ward %>


<%= link_to 'Back', wards_path %>
<%= link_to 'TOP', root_path %>

app/views/wards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Tel</th>
      <th>Sex</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wards.each do |ward| %>
      <tr>
        <td><%= ward.name %></td>
        <td><%= ward.address %></td>
        <td><%= ward.tel %></td>
        <td><%= ward.sex_i18n %></td>
        <td><%= link_to 'Edit', edit_ward_path(ward) %></td>
        <td><%= link_to 'Destroy', ward, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ward', new_ward_path %>
<br>
<%= link_to 'Back', wards_path %>
<%= link_to 'TOP', root_path %>

app/views/wards/new.html.erb
<h1>New Ward</h1>

<%= render 'form', ward: @ward %>

<%= link_to 'Back', wards_path %>
<%= link_to 'TOP', root_path %>