config/routes.rb
Rails.application.routes.draw do

  root 'top#index'

  devise_for :guardians

  resources :settings, :only => [:index]
  resources :contents, :except => [:show]
  resources :activities, :except => [:show]
  resources :guardians, :except => [:index, :new]
  resources :wards, :except => [:show]

  resources :reports, :only => [:index] do
    collection do
      get 'selection'
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id          :integer          not null, primary key
#  memo        :string
#  comment     :string
#  photo       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  guardian_id :integer
#  ward_id     :integer
#  meeting_at  :datetime
#

class Activity < ApplicationRecord
  mount_uploader :photo, ActivityPhotoUploader
  belongs_to :guardian
  belongs_to :ward
  has_many :visits
  has_many :contents, through: :visits
  scope :oneyear, -> { where('created_at > ?', 1.years.ago) }

  def create_with_visit(visit,content_id)
   ActiveRecord::Base.transaction do
    self.save!
    visit.activity_id = self.id
    visit.content_id = content_id
    visit.save!
   end
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    if params[:ward_id]
      @activities = Activity.where(ward_id: params[:ward_id]).oneyear
      @wards = Ward.find(params[:ward_id])
    else
      @activities = Activity.oneyear
    end
  end

  # GET /activities/new
  def new
    @activity = Activity.new
    @contents = Content.all
    @ward = Ward.find(params[:ward_id])
    return redirect_to activities_path(ward_id: params[:ward_id]) if params[:history]
  end

  # GET /activities/1/edit
  def edit
    @contents = Content.all
    @ward = Ward.find(@activity.ward_id)
    @content_id = @activity.visits.first.content_id
  end

  # POST /activities
  # POST /activities.json

  def create
      # activity_paramsの中身はハッシュ{:memo, :comment, :photo, :photo_cache, :ward_id, :meeting_at}
      @activity = Activity.new(activity_params)
      @visit = Visit.new
      # current_guardianはヘルパーメソッドで定義されている。hoge.name の時の hoge は引数ではなくレシーバという。
      @activity.guardian_id = current_guardian.id
      @activity.create_with_visit(@visit,params[:content_id])

      respond_to do |format|
        if @activity.persisted?
          format.html { redirect_to root_path, notice: 'Activity was successfully created.' }
          format.json { render :show, status: :created, location: @activity }
        else
          @contents = Content.all
          format.html { render :new }
          format.json { render json: @activity.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        @activity.visits.first.update(content_id: params[:content_id])
        format.html { redirect_to root_path, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @wards = Ward.find(@activity.ward_id)
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url(ward_id: @wards.id), notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:memo, :comment, :photo, :photo_cache, :ward_id, :meeting_at)
    end

end

app/views/activities/_form.html.erb
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= "#{@ward.name}さん" %>
  <div class="field">
    <%= form.label :meeting_at %>
    <%= form.datetime_select :meeting_at, id: :activity_meeting_at %>
  </div>
  <div class="field">
    <ul>
    <% @contents.each do |content| %>
      <li>
        <% if (@content_id == content.id) || @activity.new_record? %>
        <%= radio_button_tag(:content_id, content.id, checked: "checked") %>
        <%= label_tag(:activity_content, content.body) %>
        <% else %>
        <%= radio_button_tag(:content_id, content.id) %>
        <%= label_tag(:activity_content, content.body) %>
        <% end %>
      </li>
    <% end %>
    </ul>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_field :memo, id: :activity_memo %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment, id: :activity_comment %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= image_tag @activity.photo.thumb.url if @activity.photo? %>
    <%= form.file_field :photo, id: :activity_photo %>
    <%= form.hidden_field :photo_cache %>
    <%= form.hidden_field :ward_id, value: @ward.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/activities/confirm_email.html.erb
<h1>メール送信画面</h1>

<p id="notice"><%= notice %></p>

<%= link_to 'ご家族にメール送信する', send_email_activity_path(@activity), method: :post, data: { confirm: 'Are you sure?' }  %><br>
<%= link_to '内容を修正する', edit_activity_path(@activity.id,) %><br>
<%= link_to '終了してTOPに戻る', root_path %>


<h3><%= "#{@ward.name}さんの履歴" %></h3>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Memo</th>
      <th>Comment</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @activity.contents.first.body %></td>
        <td><%= @activity.memo %></td>
        <td><%= @activity.comment %></td>
        <td><%= image_tag(@activity.photo) %></td>
      </tr>
  </tbody>
</table>

<br>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path(ward_id: @activity.ward_id) %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= "#{@wards.name}さんの履歴" %></h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Memo</th>
      <th>Comment</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.contents.first.body %></td>
        <td><%= activity.memo %></td>
        <td><%= activity.comment %></td>
        <td><%= image_tag(activity.photo) %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path(ward_id: params[:ward_id]) %>

app/views/activities/mail.html.erb
<h1>メール送信画面</h1>

<p id="notice"><%= notice %></p>

<%= link_to 'ご家族にメール送信する', edit_activity_path(@activity) %><br>
<%= link_to '内容を修正する', edit_activity_path(@activity.id,) %><br>
<%= link_to '終了してTOPに戻る', root_path %>


<h3><%= "#{@ward.name}さんの履歴" %></h3>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Memo</th>
      <th>Comment</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
      <tr>
        <td><%= @activity.contents.first.body %></td>
        <td><%= @activity.memo %></td>
        <td><%= @activity.comment %></td>
        <td><%= image_tag(@activity.photo) %></td>
      </tr>
  </tbody>
</table>

<br>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>

app/views/activities/send_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <p>○○さんにお会いしてきました。</p>
  </body>
</html>

app/views/activities/send_email.text.erb
○○様

 ○○さんにお会いしてきました。